In [2]:
import numpy as np

In [177]:
np.version.version

'1.15.4'

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.ones((3, 3), dtype='bool')

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [47]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr_impar = [x for x in arr if x%2 != 0]

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr_copy = arr.copy()
arr_copy[arr_impar] = -1

In [56]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate((a, b), axis=0)
np.concatenate((a, b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [135]:
a = np.array([1,2,3])
np.concatenate((np.repeat(a, 3, axis=0), np.tile(a, 3)), axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Difícil

In [137]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [142]:
t = np.exp(sepallength)
softmax = (t/t.sum())

In [148]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [164]:
petallength = iris_2d[:, 3] > 1.5
sepallength = iris_2d[:, 1] < 5.0

iris_2d = iris_2d[petallength & sepallength]

In [165]:
iris_2d.shape

(52, 4)

In [167]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [174]:
nan = np.isnan(iris_2d)
iris_2d = iris_2d[~nan]

Muito Difícil

In [4]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)

[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]


In [14]:
np.apply_along_axis(np.bincount, 1, arr, minlength = np.max(arr) + 1)

array([[0, 1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
       [0, 2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
       [0, 1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
       [0, 2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 2, 0, 0, 2, 1]])

In [89]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

def maiores(var_arr):
    saida = []
    for i, val in enumerate(a):
        if (i == 0) or (i == (len(var_arr) - 1)):
            saida.append(False)
        else:
            ant = (val > var_arr[i-1])
            dep = (val > var_arr[i+1])
            saida.append(ant & dep)
    return saida


np.where(maiores(a))

(array([2, 5]),)

In [97]:
np.random.seed(101)
arr = np.random.randint(1,4, size=6)
print(arr)

[2 3 2 2 2 1]


In [114]:
val_unique = len(np.unique(arr))
np.eye(val_unique + 1)[arr]

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])